"""
Create a MIDI file with a melody generated by a Maximum Entropy model trained on a Bach
violin partita.
"""

import logging
from pathlib import Path

from mem.midi.midi import (
    save_midi,
    extract_pitches_from_midi,
)
from mem.training.generator import SequenceGenerator

logging.basicConfig(level=logging.INFO)

if __name__ == "__main__":
    midi_pitches = extract_pitches_from_midi(Path("data/midi/bach_partita_violin.mid"))
    # midi_pitches = extract_pitches_from_midi(Path("data/midi/bach_prelude_c.mid"))
    # for i in range(1, 11):
    #     g = SequenceGenerator(midi_pitches, k_max=i, fast=True).train(max_iter=10)
    #     save_midi(g.sample_seq(300), Path(f"generated/bach_partita_violin_k{i}.mid"))
    g = SequenceGenerator(midi_pitches, k_max=10, fast=True).train(max_iter=10)
    save_midi(g.sample_seq(300), Path(f"generated/bach_partita.mid"))
