"""
Create a MIDI file with a melody generated by a Maximum Entropy model trained on a Bach
violin partita.
same as bach, but learns intervals instead of pitches
"""

import logging
from pathlib import Path

from mem.midi.midi import (
    save_midi,
    extract_pitches_from_midi,
)
from mem.training.generator import SequenceGenerator

logging.basicConfig(level=logging.INFO)

if __name__ == "__main__":
    # midi_pitches = extract_pitches_from_midi(Path("data/midi/bach_prelude_c.mid"))
    midi_pitches = extract_pitches_from_midi(Path("data/midi/bach_partita_violin.mid"))
    intervals = [b - a for a, b in zip(midi_pitches, midi_pitches[1:])]
    g = SequenceGenerator(intervals, k_max=15, fast=True).train(max_iter=10)
    res = g.sample_seq(50)
    start_pitch = 71
    generated_pitches = [start_pitch]
    for interval in res:
        generated_pitches.append(generated_pitches[-1] + interval)
    print(generated_pitches)
    save_midi(generated_pitches, Path(f"generated/bach_partita_intervals.mid"))
