"""
Create a MIDI file with a melody generated by a Maximum Entropy model trained on a Bach
violin partita.
"""

from mem.midi.midi import (
    save_midi,
    extract_pitches_from_midi,
)

from pathlib import Path

from mem.training.generator import SequenceGenerator

if __name__ == "__main__":
    midi_pitches = extract_pitches_from_midi(
        Path("../data/midi/bach_partita_violin.mid")
    )
    g = SequenceGenerator(midi_pitches, k_max=10, max_iter=100).train()
    for i in range(10):
        save_midi(g.sample_seq(100), Path(f"./output-{i}.mid"))
