"""
Create a MIDI file with a melody generated by a Maximum Entropy model trained on a Bach
Jesus choral.
"""

import logging
from pathlib import Path

from mem.midi.midi import (
    save_midi,
    extract_pitches_from_midi,
)

logging.basicConfig(level=logging.INFO)
from mem.training.generator import SequenceGenerator

if __name__ == "__main__":
    midi_pitches = extract_pitches_from_midi(Path("data/midi/bach_jesus_joy.mid"))
    g = SequenceGenerator(midi_pitches, k_max=10).train(max_iter=100)
    for i in range(10):
        save_midi(g.sample_seq(100), Path(f"generated/bach-jesus" f"-{i}.mid"))
