"""
Create a MIDI file with a melody generated by a Maximum Entropy model trained on a Bach
violin partita.
"""

from mem.midi.midi import (
    extract_pitches_from_midi,
    save_midi,
)

from pathlib import Path

from mem.training.generator import SequenceGenerator

import logging

logging.basicConfig(level=logging.DEBUG)

if __name__ == "__main__":
    midi_pitches = extract_pitches_from_midi(Path("data/midi/bach_partita_violin.mid"))
    g = SequenceGenerator.on_sequence(midi_pitches, k_max=2)
    g.train(max_iter=10)
    g.save_model("./model.npz")
    # g.load_model("./model.npz")
    save_midi(g.sample_seq(200), "./partita.mid")
